In [73]:
from PIL import Image
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import image as mimage
import importlib
import utils
importlib.reload(utils)
from utils import grayscale2binary as g2b
from utils import rgb2binary as rgb2b

In [3]:
src = "media\\Lenna.png"

In [4]:
img = Image.open(src)

In [60]:
img.show()

In [ ]:
imgArray = np.asarray(img)
print(imgArray.shape)
print(imgArray.dtype)
a =  Image.fromarray(imgArray)
# print(imgArray.shape)
imgProcessed = utils.rgb2binary(imgArray,0.5,0.5,0.5)
print(imgProcessed.shape)
print(imgProcessed.dtype)
# imgProcessed
# print(imgProcessed.shape)
t = Image.fromarray(imgProcessed)

(512, 512, 3)
uint8
(512, 512, 3)
uint8


In [59]:
p = np.asanyarray(t)
p

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.]], dtype=float32)

In [86]:
t.show()

In [11]:
imgProcessed[0,0,:]

array([125, 125, 125], dtype=uint8)

In [17]:
r = imgArray[:,:,0]
g = imgArray[:,:,1]
b = imgArray[:,:,2]

r_bin = utils.grayscale2binary(r,0.3)
g_bin = utils.grayscale2binary(g,0.3)
b_bin = utils.grayscale2binary(b,0.3)

In [19]:
print(r_bin)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [20]:
Image.fromarray(r_bin*255).show()

AttributeError: 'PngImageFile' object has no attribute 'getPixel'